=== 0ccupi3R/misp-galaxy/schema_clusters.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-galaxies",
  "id": "https://www.github.com/MISP/misp-galaxies/schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "values": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "description": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "meta": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "refs": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "type": "string"
                }
              },
              "synonyms": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "type": "string"
                }
              },
              "derivated_from": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "type": "string"
                }
              },
              "status": {
                "type": "string"
              },
              "country": {
                "type": "string"
              },
              "effectiveness": {
                "type": "string"
              },
              "complexity": {
                "type": "string"
              },
              "type": {
                "type": "array",
                "uniqueItems": true,
                "items": {
                  "type": "string"
                }
              },
              "impact": {
                "type": "string"
              },
              "motive": {
                "type": "string"
              },
              "colour": {
                "type": "string"
              },
              "possible_issues": {
                "type": "string"
              }
            }
          }
        },
        "required": [
          "value"
        ]
      }
    },
    "authors": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "description",
    "type",
    "version",
    "name",
    "uuid",
    "values",
    "authors",
    "source"
  ]
}

=== 0ccupi3R/misp-galaxy/clusters/botnet.json
{
  "values": [
    {
      "value": "ADB.miner",
      "description": "A new botnet appeared over the weekend, and it's targeting Android devices by scanning for open debug ports so it can infect victims with malware that mines the Monero cryptocurrency.\n\nThe botnet came to life on Saturday, February 3, and is targeting port 5555, which on devices running the Android OS is the port used by the operating system's native Android Debug Bridge (ADB), a debugging interface that grants access to some of the operating system's most sensitive features.\n\nOnly devices running the Android OS have been infected until now, such as smartphones, smart TVs, and TV top boxes, according to security researchers from Qihoo 360's Network Security Research Lab [Netlab] division, the ones who discovered the botnet, which the named ADB.miner.",
      "meta": {
        "refs": [
          "https://www.bleepingcomputer.com/news/security/android-devices-targeted-by-new-monero-mining-botnet/"
        ]
      }
    }
  ],
  "name": "Botnet",
  "type": "botnet",
  "source": "MISP Project",
  "authors": [
    "Various"
  ],
  "description": "botnet galaxy",
  "uuid": "a91732f4-164a-11e8-924a-ffd4097eb03f",
  "version": 1
}
